#!/bin/bash
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"abhijit.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "abhijit"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"akshath.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "akshath"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"anand.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "anand"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"chandra.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "chandra"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"ekta.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "ekta"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"gaurav.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "gaurav"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"girish.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "girish"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"harshad.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "harshad"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"iyer anand.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "iyer anand"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"krishnan.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "krishnan"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"kunal.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "kunal"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"naren.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "naren"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"ninad.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "ninad"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"pradeep.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "pradeep"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"pramod.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "pramod"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"pritish.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "pritish"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"rahul.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "rahul"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"ritesh.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "ritesh"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"sandip.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "sandip"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"santanu.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "santanu"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"sharad.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "sharad"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"sheraz.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "sheraz"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"sunil.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "sunil"
aws rekognition index-faces --image '{"S3Object":{"Bucket":"wildwestfaces","Name":"tapan.jpg"}}' --collection-id "wildwest" --detection-attributes "ALL" --external-image-id "tapan"
